name: Create New Version

on:
  pull_request: 
    branches: ["main"]
  push:
    branches: [ "main" ]
    
  workflow_dispatch:


jobs:
  publish-package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
        
      - name: Clean install
        run: npm ci
        
      - name: Clean build
        run: npm run build
        
      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          greater-version-only: true